[tool.poetry]
name = "api_framework"
version = "0.1.0"
description = ""
authors = ["tingjio <1292871494@qq.com>"]

[tool.poetry.dependencies]
python = "3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
